<<<<<<< Updated upstream
version: '3.8'
=======
services:
  db:
    image: postgres:16-alpine
    container_name: taskapi_postgres
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Garvenpeter1234
    ports:
      - "5432:5432"
    volumes:
      - taskapi_db_data:/var/lib/postgresql/data
>>>>>>> Stashed changes

services:
  app:
    build: .
<<<<<<< Updated upstream
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://db:1521/mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
    restart: always

  db:
    image: oscarfonts/h2
    ports:
      - "1521:1521"
    environment:
      H2_OPTIONS: -ifNotExists
=======
    container_name: taskapi_app
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/taskdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Garvenpeter1234
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  taskapi_db_data:
>>>>>>> Stashed changes
